#!/bin/bash
cd /tmp/rom
rm -rf .repo &

source build/envsetup.sh
lunch havoc_lava-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	make bacon -j16
	zip=$(up out/target/product/lava/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
sleep 4500 && kill "$!"
