#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo # lets remove unnecessary things, so that no storage issue can occur


cd external/selinux 
curl -L http://ix.io/2FhM > sasta.patch 
git am sasta.patch 

cd /tmp/rom


# Normal build steps
. build/envsetup.sh
lunch octavi_RMX2151-userdebug
export SAKURA_BUILD_TYPE=gapps
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	brunch RMX2151
	zip=$(up out/target/product/lava/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom 
#sleep 5200 && kill "$!"
kill "$!" && bash upload_ccache
