#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur




# Normal build steps
source build/envsetup.sh
lunch lineage_lava-userdebug
cd frameworks/opt/net/wifi && git reset --hard
cd /tmp/rom
cd frameworks/base && git reset --hard
cd /tmp/rom
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	make bacon -j16
	zip=$(up out/target/product/lava/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
sleep 5200 && kill "$!"
