#!/bin/bash

url=https://mirror.cryllicbuster273.me/gay.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf gay.tar.gz
echo "unzip done"
find gay.tar.gz -delete
