#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/part1.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf part1.tar.gz
echo "unzip done"
find part1.tar.gz -delete
