#!/bin/bash

url=https://mirror.cryllicbuster273.me/sakura-ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf sakura-ccache.tar.gz
echo "unzip done"
find sakura-ccache.tar.gz -dele
