#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/HyconOS/manifest
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Box In A Box"
git config --global user.email evanferrao@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
pwd

git clone --depth=1 --single-branch https://github.com/Redmi-MT6768/android_device_xiaomi_merlin.git -b eleven device/xiaomi/lava 
git clone --depth=1 --single-branch https://github.com/Redmi-MT6768/android_vendor_xiaomi_lava.git -b eleven vendor/xiaomi/lava
git clone https://github.com/henloscape/memecam.git vendor/xiaomi/miuicamera
pwd
cd device/xiaomi/lava && sed -i s/aosp/lineage/g AndroidProducts.mk && sed -i s/aosp/lineage/g aosp_lava.mk && mv aosp_merlin.mk lineage_lava.mk && cd ../../..
cd device/xiaomi/lava && echo 'TARGET_USES_FACE_UNLOCK := true' >> aosp_lava.mk && cd overlay/packages/apps/Settings/res/values && echo '<string name="hycon_maintainer">Box_Boi</string>' strings.xml
cd device/xiaomi/lava && sed -i '76,77,81,82d' Boardconfig.mk && cd prebuilt && wget https://cheems.mirrorbomt.workers.dev/Image.gz-dtb && cd /tmp/rom
pwd

# mt6768 autopatcher by henloboi 202103040948 GMT+0

pfwb() {
    cd frameworks/base && wget https://github.com/PixelExperience/frameworks_base/commit/37f5a323245b0fd6269752742a2eb7aa3cae24a7.patch && git apply 37f5a323245b0fd6269752742a2eb7aa3cae24a7.patch
}

pims() {
    cd frameworks/opt/net/ims && wget https://github.com/PixelExperience/frameworks_opt_net_ims/commit/661ae9749b5ea7959aa913f2264dc5e170c63a0a.patch && git apply 661ae9749b5ea7959aa913f2264dc5e170c63a0a.patch
}

pwifi() {
    cd frameworks/opt/net/wifi && wget https://github.com/PixelExperience/frameworks_opt_net_wifi/commit/3bd2c14fbda9c079a4dc39ff4601ba54da589609.patch && git apply 3bd2c14fbda9c079a4dc39ff4601ba54da589609.patch
}

mtkr() {
    git clone --depth=1 --single-branch https://github.com/PixelExperience/device_mediatek_sepolicy device/mediatek/sepolicy 
    git clone --depth=1 --single-branch https://github.com/PixelExperience/vendor_mediatek_interfaces vendor/mediatek/interfaces 
    git clone --depth=1 --single-branch https://github.com/PixelExperience/vendor_mediatek-opensource vendor/mediatek/opensource
    git clone --depth=1 --single-branch https://github.com/Redmi-MT6768/android_vendor_mediatek_ims vendor/mediatek/ims 
}
pwd
cd /tmp/rom
pfwb
cd /tmp/rom
pims 
cd /tmp/rom
pwifi 
cd /tmp/rom
mtkr
cd /tmp/rom

echo "patch done !"
pwd

